### ISSUE TITLE
表格内容空

### ISSUE THREAD

**Issue by Gaojunsu** [caryyu/excel2pdf#2]
其实是有内容的，只是字体设置有些问题。
//字体颜色，注释掉之前的，我直接设置为黑色字体
        result.setColor(0,0,255); 
              /*   int colorIndex = font.getColor();
                                 if(font.getBoldweight() == org.apache.poi.ss.usermodel.Font.BOLDWEIGHT_BOLD){
                                 result.setStyle(Font.BOLD);
                                 }
                               HSSFColor color = HSSFColor.getIndexHash().get(colorIndex);
                                 result.setColor(BaseColor.BLACK);
                                if(color != null){
                                    int rbg = POIUtil.getRGB(color);
                                    result.setColor(new BaseColor(rbg));
                                }*/

**Comment by 13rj115** [comment]
应该是HSSFColor 和 XSSFColor 不同导致的。
        if (color instanceof HSSFColor) {
            HSSFColor hssfColor = (HSSFColor) color;
            short[] rgb = hssfColor.getTriplet();
            red = rgb[0];
            green = rgb[1];
            blue = rgb[2];
            result = new java.awt.Color(red, green, blue).getRGB();
        }

这样就可以了

**Comment by caryyu** [comment]
这个问题应该已经解决了。
