### ISSUE TITLE
转成的pdf 字体白色。所以PDF 文件看着是空白

### ISSUE THREAD

**Issue by wyb20091204** [caryyu/excel2pdf#5]
POIUtil 这个class 里面 public static int getRGB(Color color){} 这个函数  我强行return 0 0 0 黑色result = new java.awt.Color(0, 0, 0).getRGB(); 这样导出来的PDF 的文件字体就有字了。我的excel 文件是 随便写的一个文件，不过我把它保存成了低版本 后缀是.xls  的文件。希望计算字体颜色这里能有个解决方法

**Comment by caryyu** [comment]
你使用的是 Microsoft Office 套件哪个版本,或使用其它的?

**Comment by wyb20091204** [comment]
> 你使用的是 Microsoft Office 套件哪个版本,或使用其它的?

16版的office

**Comment by caryyu** [comment]
@wyb20091204  目前已经做了更新，代码还未合并至 master，你可以从 PR 拿出来进行测试，没问题的话，我就合并到 master 了。

**Comment by caryyu** [comment]
我先关闭了，有问题再重开。

**Comment by wyb20091204** [comment]
这几天没有看邮件 不好意思。我工程里现在改了挺多地方的。回复到去年我问你的时候那个状态可能有点难。我另外回头抽时间再试试可以吗

在 2019-04-20 21:50:15，"Cary" <notifications@github.com> 写道：


我先关闭了，有问题再重开。
